### ISSUE TITLE
Script Installation Problems, not realy userfriendly

### ISSUE THREAD

**Issue by Pimmal** [jprjr/multistreamer-installer#15]
hi i have installed it with ./setup stream1......... instalation was sucesfully
if i go to my browser with stream1..... then i get 502 Bad gateway and in nginx config
`conflicting server name "stream1..........." on [::]:443, ignored`
So if i adjust the sites-available config to server1...... nginx is starting and in the browser i get "ERR_EMPTY_RESPONSE"

So i have no idea anymore, pls help me out.

**Comment by Pimmal** [comment]
Now i´m getting
`postgres-auth-server[27464]: Unable to connect to postgres: FATAL: password authentication failed for user "psql_auth"`
Seems for me not realy userfriendly this install script

**Comment by Pimmal** [comment]
I have done the steps below after .setup stream1.......

`mkdir /etc/multistreamer
cp /opt/multistreamer/etc/config.yaml /etc/multistreamer/config.yaml`
then you need to edit the config and also change the path from nginx to the correct one: 
`nginx: '/opt/openresty-rtmp/nginx/sbin/nginx' normaly it`s nginx: '/opt/openresty/nginx/sbin/nginx'`

Afterwards copy the authserverconfig
`mkdir cp /etc/postgres-auth-server
cp /opt/postgres-auth-server/etc/config.yaml.example /etc/postgres-auth-server/config.yaml`
then you need to create the psql user and DB
`sudo -u postgres psql -c "create user psql_auth with password '12345'"
sudo -u postgres psql -c "create database psql_auth with owner psql_auth"`
then adjust the file /etc/postgres-auth-server/config.yaml with your psql password.

now i get the following error message on http://stream1........:8080/user
`Error
[string "etlua"]:92: attempt to index global 'user' (a nil value)
Traceback
stack traceback:
	[string "etlua"]:92: in function 'run'
	...es-auth-server/lua_modules/share/lua/5.1/lapis/etlua.lua:158: in function 'thing'
	...-auth-server/lua_modules/share/lua/5.1/lapis/request.lua:90: in function 'write'
	...-auth-server/lua_modules/share/lua/5.1/lapis/request.lua:237: in function 'render'
	...h-server/lua_modules/share/lua/5.1/lapis/application.lua:136: in function <...h-server/lua_modules/share/lua/5.1/lapis/application.lua:135>
	[C]: in function 'xpcall'
	...h-server/lua_modules/share/lua/5.1/lapis/application.lua:173: in function 'dispatch'
	...es-auth-server/lua_modules/share/lua/5.1/lapis/nginx.lua:230: in function 'serve'
	content_by_lua(nginx.conf:49):2: in function <content_by_lua(nginx.conf:49):1>`

**Comment by k1ck3r** [comment]
ok let me clarify few things. i didn't wrote those scripts or the multistreamer application, but love it big time. yes, the scripts are not constantly updated regarding the new version of the modules and same goes for the docker image i think (once i failed few times with docker long time ago, i just took the hard way and literally ate every thing which made problems compiling and further more making multistreamer unfriendly.

so, first of all, if you are willing to really use it (personally would highly recommend you to do so - keeping updated version for my WoW guild, since we live in Bulgaria, and not all of us can afford high speed international traffic) grab some attention to details, and first thing configure every config to use verbose logging. using John's scripts most of the times falling to compile is related to missing link or some differences in the libs used to compile. 

now will let you know every tricky issues i had at the time which worth to mention:
1. PostgreSQL - by default every installation of psql is "highly secured" meaning that if you don't adjust its config, most probably Multisteramer will fail to connect. to save you some time will only mention the the line with with md5 encryption for 127.0.0.1 is the thing you are looking for. last line it's ssl related, and if you are not security freak, not necessary at all:

```
local   all             all                                     peer
host    all             all             127.0.0.1/32            md5
hostssl all             all             0.0.0.0/0               md5     clientcert=1
```

2. Multistreamer and Postgre-auth-server are using openresty as a base with some additional modules, enhancing the streaming flow. However their purpose is not meant to serve on port 80 and 443. depending on your software choice you have to create proxy-passing from ports 80 and 443 to exact Mulstreamer's and Auth's ports. again will just save you time and give you and simple example which will work 100% (personally using HAProxy):
```
location /users {
    proxy_pass http://127.0.0.1:8080;
    proxy_request_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_redirect http:// $scheme://;
  }
```
```
location / {
    proxy_pass http://127.0.0.1:8081;
    proxy_request_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_redirect http:// $scheme://;
  }
```
First part is related with GUI for postgre-auth-server, 2nd part for multistreamer. and this config should go for to nginx. the examples are ONLY for non-ssl ports.

3. i didn't saw any information related to [sockexec](https://github.com/jprjr/sockexec). let me know if installed and do you know exactly what role in the full stack takes. 

4. strongly suggest you to turn off ipv6 (on every part of the service, for me, i turned off ipv6 for whole virtual machine which handles multistreamer) since some of providers (specifically mixer) have issues and breaks the Multistreamer. 

i think i covered most of the issues i had, and willing to help you further. if you didn't had the luck after this, i can offer you discord communication, but that's up to you. nowwww, go get compiled!

**Comment by jprjr** [comment]
Hi, sorry I've been MIA. My previous job gave me time to work on 
open-source projects, my current doesn't, so I have way less free time 
to work on this.

I'm tempted to just archive this installer repo, it's a pain in the 
ass to maintain. I just use a manual install myself.

-John

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
