### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by brandongunderson** [jprjr/multistreamer-installer#8]
I'm having trouble while installing. It keeps erroring out at this point. 

Generating multistreamer config file (/etc/multistreamer/config.yaml) ...
./setup: 512: ./setup: /opt/openresty-rtmp/bin/lua: not found

![install_error](https://user-images.githubusercontent.com/22452783/47193465-040ad380-d321-11e8-8cb5-9c4d492c817a.PNG)

**Comment by tomasguirao** [comment]
Same error.. Some solution?

**Comment by jprjr** [comment]
In my script, I install `luarocks` as a rock, but it looks like `luaposix` had an update that broke building `luaposix` when you install `luarocks` as a rock.

Just updated one of the install scripts to install `luarocks` the standard way, which should fix the `postgres-auth-server` install breaking.

I'll have to take a look at the `./setup` script, that requires more effort to troubleshoot since it includes setting up Let's Encrypt and whatnot.

**Comment by lhorace** [comment]
Hi @jprjr,

> Just updated one of the install scripts to install `luarocks` the standard way, which should fix the `postgres-auth-server` install breaking.

Can you reference the commit that fixes this? I can't seem to find it on my end?

Regards

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
